all:
  children:
    master:
      hosts:
        192.168.0.40:
          ansible_user: pi
          ansible_ssh_pass: Lomo2715!
    workers:
      hosts:
        192.168.0.41:
          ansible_user: pi
          ansible_ssh_pass: Lomo2715!
        192.168.0.42:
          ansible_user: pi
          ansible_ssh_pass: Lomo2715!
        192.168.0.43:
          ansible_user: pi
          ansible_ssh_pass: Lomo2715!
  vars:
    ansible_python_interpreter: /usr/bin/python3
