---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edwards-api-ingress
  namespace: website
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "2000"
spec:
  ingressClassName: traefik
  rules:
  - host: edwardstech.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3001
  - host: www.edwardstech.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edwards-frontend-ingress
  namespace: website
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "1000"
spec:
  ingressClassName: traefik
  rules:
  - host: edwardstech.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: www.edwardstech.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80